#!/bin/bash
rm ../../scores/*
FILES=../../results/*
for f in $FILES
do
  echo "Processing $f"
  exe/./distance $f ../../scores/all.txt
done
exe/./sort ../../scores/all.txt ../../scores/sorted.txt
echo "Done"